version: '3'

services:

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8001:8000"

  course-service:
    build: ./course-service
    container_name: course-service
    ports:
      - "8002:8000"

  enrollment-service:
    build: ./enrollment-service
    container_name: enrollment-service
    ports:
      - "8003:8000"
    depends_on:
      - user-service
      - course-service
